// AUTO-GENERATED by scripts/sync-tool-catalog.ts — do not edit.
// Run `npm run catalog:sync` after changing MCP tool registrations.

import type { ToolParamInfo } from "@/lib/mcp-types";

export type EssentialTool = { name: string; description: string };
export type ExtendedTool = {
	name: string;
	category: string;
	description: string;
	readOnly: boolean;
	destructive: boolean;
};

export const TOOL_CATALOG: {
	essentials: EssentialTool[];
	extended: ExtendedTool[];
	schemas: Record<string, Record<string, ToolParamInfo>>;
} = {
	"essentials": [
		{
			"name": "briefMe",
			"description": "One-shot session primer — handoff, diff, top work, blockers, recent decisions, pulse."
		},
		{
			"name": "saveHandoff",
			"description": "Session wrap-up — saves handoff, links commits, reports touched cards, returns resume prompt."
		},
		{
			"name": "createCard",
			"description": "Create a card in a column (by name)."
		},
		{
			"name": "updateCard",
			"description": "Update card fields; optional `intent`."
		},
		{
			"name": "moveCard",
			"description": "Move a card to a column. Requires `intent`."
		},
		{
			"name": "addComment",
			"description": "Add a comment to a card."
		},
		{
			"name": "registerRepo",
			"description": "Bind a git repo path to a project (call after briefMe returns needsRegistration)."
		},
		{
			"name": "checkOnboarding",
			"description": "Detect DB state, list projects/boards, session-start discovery."
		},
		{
			"name": "getTools",
			"description": "Browse extended tools by category."
		},
		{
			"name": "runTool",
			"description": "Execute any extended tool by name."
		}
	],
	"extended": [
		{
			"name": "listActivity",
			"category": "activity",
			"description": "Recent activity for a board: what changed, who did it, when.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "bulkCreateCards",
			"category": "cards",
			"description": "Create multiple cards in one call. v4.2: prefer `tagSlugs` and `milestoneId`; legacy `tags` and `milestoneName` still work with `_deprecated` warnings.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "bulkMoveCards",
			"category": "cards",
			"description": "Move multiple cards to a column in one call.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "bulkUpdateCards",
			"category": "cards",
			"description": "Update multiple cards in one call. Each entry can set priority, tags, and/or milestone. Omitted fields are unchanged. v4.2: prefer `tagSlugs` and `milestoneId`; legacy params still accepted with `_deprecated` warnings.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "createCardFromTemplate",
			"category": "cards",
			"description": "Create a card from a pre-filled template. Templates: Bug Report, Feature, Spike / Research, Tech Debt, Epic.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "deleteCard",
			"category": "cards",
			"description": "Permanently delete a card and all its data. Cannot be undone. Agents must pass `intent` explaining why.",
			"readOnly": false,
			"destructive": true
		},
		{
			"name": "addChecklistItem",
			"category": "checklist",
			"description": "Add a checklist item to a card.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "bulkAddChecklistItems",
			"category": "checklist",
			"description": "Add checklist items to one or more cards. Pass an array of { cardId, items } objects.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "toggleChecklistItem",
			"category": "checklist",
			"description": "Toggle a checklist item complete or incomplete.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "listComments",
			"category": "comments",
			"description": "List comments on a card. (getBoard returns only counts, not content.)",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "getCardContext",
			"category": "context",
			"description": "Deep context for a single card: description, checklist, comments, relations, decisions, commits, and related cards.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "getMilestoneContext",
			"category": "context",
			"description": "Cards and progress for a milestone, grouped by horizon (now/later/done). Includes decisions.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "getTagContext",
			"category": "context",
			"description": "All cards with a given tag, grouped by column. Input is normalized to a slug — 'Bug', 'bug', and 'BUG' all match the same tag.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "listClaims",
			"category": "context",
			"description": "List claims for a project. Omit kind to include all kinds. Pass claimId for single-claim lookup.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "listFacts",
			"category": "context",
			"description": "List facts for a project. Omit type to list all types. Filter by path or surface. Pass factId for single-fact lookup. (Reads from the unified Claim table — prefer listClaims for new code.)",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "planCard",
			"category": "context",
			"description": "Plan a card: returns the card context, tracker.md policy, extracted investigation hints, and a structured protocol the agent follows to draft a four-section plan (Why now / Plan / Out of scope / Acceptance). Refuses with PLAN_EXISTS warning if the card already has a plan.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "queryKnowledge",
			"category": "context",
			"description": "Full-text search across all project knowledge: cards, comments, decisions, notes, handoffs, code facts, context entries, and indexed repo markdown files. Auto-rebuilds the index on cold start (zero indexed rows for the project).",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "rebuildKnowledgeIndex",
			"category": "context",
			"description": "Force a full rebuild of the FTS5 knowledge index for a project — clears the existing index and re-ingests cards, comments, claims, notes, handoffs, and repo markdown. Use after batch operations (createMany/updateMany/deleteMany bypass live sync), repo markdown changes, or to recover from drift.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "saveClaim",
			"category": "context",
			"description": "Create or update a Claim — a typed assertion with evidence. Pass claimId to update.\n\nThis is the RFC-v2 replacement for saveFact/recordDecision. Old tools still work; use saveClaim for new writes when you want the unified shape (statement + body + evidence + payload).\n\nKinds:\n- context: project-level knowledge claim (payload: { application?, audience?, surface? })\n- code: assertion about a file or symbol (evidence.files or evidence.symbols required)\n- measurement: numeric value (payload.value + payload.unit required)\n- decision: architectural decision (payload: { alternatives? })",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "saveFact",
			"category": "context",
			"description": "Create or update a persistent fact. Pass factId to update.\n\nTypes:\n- **context**: Project-level knowledge claim (content = the claim, plus rationale/application/details)\n- **code**: Assertion about a file or symbol (content = the fact, path required)\n- **measurement**: Numeric value like latency or bundle size (content = description, value + unit required)",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "getDecisions",
			"category": "decisions",
			"description": "List decisions for a project, optionally filtered by card or status.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "recordDecision",
			"category": "decisions",
			"description": "Record an architectural decision.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "updateDecision",
			"category": "decisions",
			"description": "Update a decision's status, text, or rationale.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "doctor",
			"category": "diagnostics",
			"description": "Install health check — runs 8 checks for legacy config drift, version skew, and FTS state. Returns structured { checks, summary } with copy-pasteable fix commands per failed check.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "auditBoard",
			"category": "discovery",
			"description": "Board health check: find cards missing priority, tags, milestones, or checklists. Groups by issue type for quick triage. Also returns project-level taxonomy signals (single-use tags, near-miss slug pairs, stale-active milestones) so drift between explicit audits is visible. Supports custom weights for health score.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "getBoard",
			"category": "discovery",
			"description": "Board state with filtering. Use 'columns' to fetch specific columns, 'excludeDone' to skip Done/Parking, 'summary' for lightweight view (no descriptions/checklists).",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "getCard",
			"category": "discovery",
			"description": "Full card detail: description, checklist, comments, activity history.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "getRoadmap",
			"category": "discovery",
			"description": "Roadmap view: cards grouped by milestone and horizon. Includes blockedBy refs and progress per milestone. Horizons: In Progress/Review=Now, Up Next=Next, Backlog=Later, Done=Done.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "getStats",
			"category": "discovery",
			"description": "Board statistics: card counts per column, priority breakdown. Lighter than getBoard.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "getToolUsageStats",
			"category": "discovery",
			"description": "MCP tool call analytics. mode=summary: top tools by call count with error rates and latency. mode=tool: single-tool deep dive with p50/p95 duration and recent errors. mode=agents: per-agent breakdown with top tools per agent.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "getWorkNextSuggestion",
			"category": "discovery",
			"description": "Get top cards to work on next, ranked by a composite score of priority, age, blockers, due dates, and progress.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "listBoards",
			"category": "discovery",
			"description": "List boards for a project with column summaries.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "listProjects",
			"category": "discovery",
			"description": "List all projects with board and card counts.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "listWorkflows",
			"category": "discovery",
			"description": "List named, multi-step recipes for common agent procedures (sessionStart, sessionEnd, firstSession, recordDecision, searchKnowledge). Returns ordered steps + intent per step + an optional `suggested` hint nominating the most relevant workflow given current board state. Use this — not `getTools` — when you want to know what to do, not which tool to call.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "queryCards",
			"category": "discovery",
			"description": "Filter cards by priority, column, tags, milestone, age. Lightweight response.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "renderStatus",
			"category": "discovery",
			"description": "Generate a STATUS.md-equivalent markdown snapshot of a project — milestones, components, metrics, parking lot. Replaces hand-maintained STATUS.md files with board-derived output.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "searchCards",
			"category": "discovery",
			"description": "Search cards by title/description across all projects. Tag filter is normalized to a slug — 'Bug', 'bug', and 'BUG' all match the same tag.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "getCommitSummary",
			"category": "git",
			"description": "Structured summary of all commits linked to a card: commit count, authors, time span, and files grouped by category (source, schema, styles, tests, config, docs, other).",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "getGitLog",
			"category": "git",
			"description": "Recent git commits with detected card references.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "syncGitActivity",
			"category": "git",
			"description": "Scan git commits for #N card refs and create links.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "createMilestone",
			"category": "milestones",
			"description": "Create a milestone for a project.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "listMilestones",
			"category": "milestones",
			"description": "List milestones for a project with card counts, done/total breakdown, completion percentage, state, and v4.2 governance hints (singleton-after-days, possible-merge near-miss neighbours). Use the hints to drive a one-time triage pass with mergeMilestones / updateMilestone({ state: 'archived' }).",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "mergeMilestones",
			"category": "milestones",
			"description": "Merge one milestone into another within the same project. Rewrites every card's milestoneId from `from` to `into`, then deletes the source milestone. Use this when an agent or human created a duplicate (e.g. 'Getting Started' vs 'getting started' on a pre-v4.2 schema).",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "updateMilestone",
			"category": "milestones",
			"description": "Update a milestone's name, description, target date, or state. Pass `state: \"archived\"` to hide the milestone from the picker without deleting it.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "createNote",
			"category": "notes",
			"description": "Create a note. Defaults: kind=general, author=HUMAN, metadata={}. Omit projectId for a global note.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "listNotes",
			"category": "notes",
			"description": "List notes. Filter by kind/cardId/boardId/author. Omit projectId to list across projects.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "updateNote",
			"category": "notes",
			"description": "Update a note. Omitted fields unchanged.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "getBlockers",
			"category": "relations",
			"description": "List cards that are blocked and what blocks them.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "linkCards",
			"category": "relations",
			"description": "Create a dependency between two cards.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "unlinkCards",
			"category": "relations",
			"description": "Remove a dependency between two cards.",
			"readOnly": false,
			"destructive": true
		},
		{
			"name": "listHandoffs",
			"category": "session",
			"description": "List recent handoff summaries for a board. Shows the trajectory of work across sessions.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "loadHandoff",
			"category": "session",
			"description": "Load latest handoff and changes since then. Prefer the essential `briefMe` tool for session-start — it includes this plus top work, blockers, and pulse.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "recordTokenUsage",
			"category": "session",
			"description": "Record token usage for the current MCP session. Use when the agent's transcript isn't accessible (Codex, custom agents) — Claude Code uses recordTokenUsageFromTranscript via Stop hook instead. Always additive: each call creates one new row, so callers shouldn't loop and should sum their counts before calling.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "recordTokenUsageFromTranscript",
			"category": "session",
			"description": "Stream a Claude Code session transcript JSONL (plus any sibling sub-agent transcripts) and record per-model token usage. Idempotent on sessionId — re-running replaces rows. Designed for the Claude Code Stop hook (type: 'mcp_tool'); accepts the hook's transcript_path / session_id / cwd substitution variables. Returns soft warnings (NO_USAGE_FOUND, PROJECT_NOT_FOUND, TRANSCRIPT_NOT_FOUND) instead of erroring so the hook never blocks.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "createColumn",
			"category": "setup",
			"description": "Add a custom column. Standard columns are created by createProject.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "createProject",
			"category": "setup",
			"description": "Create a project with default board and columns (Backlog, In Progress, Done, Parking Lot).",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "seedTutorial",
			"category": "setup",
			"description": "Create the \"Learn Pigeon\" tutorial project with sample cards, checklists, milestones, and more. Idempotent — safe to call multiple times.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "setRepoPath",
			"category": "setup",
			"description": "Set the local git repository path for a project.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "createTag",
			"category": "tags",
			"description": "Explicitly create a tag in a project. Slug is derived from the label via slugify (lowercase, kebab-case). Idempotent — returns the existing tag if a row with the same slug already exists.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "deleteTag",
			"category": "tags",
			"description": "Delete a tag — only when zero cards reference it. To delete a tag that's still in use, call `mergeTags` first to drain its references into another tag, then delete the (now orphan) source if the merge didn't already remove it. The check is atomic against concurrent CardTag inserts: a tag picking up usage mid-request is rejected with USAGE_NOT_ZERO rather than getting deleted with rows still pointing at it.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "listTags",
			"category": "tags",
			"description": "List tags in a project with usage counts and governance hints. Backs the autocomplete combobox and agent-side discovery for tagSlugs.\n\nOptional `state` filter ('active' | 'archived') defaults to 'active' when omitted.\n\nEach row may include `_governanceHints` when something deserves the agent's attention:\n- `singleton: true` — the tag is referenced by exactly one card; consider whether the vocabulary is premature.\n- `possibleMerge: [{ id, label, distance }]` — peers within Levenshtein distance ≤ 2 of this tag's slug; collapse near-duplicates with `mergeTags`.\nAbsent fields mean no signal — agents should not treat missing hints as an empty array.",
			"readOnly": true,
			"destructive": false
		},
		{
			"name": "mergeTags",
			"category": "tags",
			"description": "Merge one tag into another within the same project. Rewrites every CardTag row from `from` to `into`, then deletes the source tag. Composite-PK collisions on (cardId, tagId) are handled per-row — the destination row wins, the source row is removed.",
			"readOnly": false,
			"destructive": false
		},
		{
			"name": "renameTag",
			"category": "tags",
			"description": "Update a tag's display label. Slug is immutable — to change the slug, create a new tag and merge the old one into it.",
			"readOnly": false,
			"destructive": false
		}
	],
	"schemas": {
		"listActivity": {
			"boardId": {
				"type": "Board UUID",
				"required": true,
				"description": "Board UUID"
			},
			"limit": {
				"type": "Max items (1–100)",
				"required": false,
				"description": "Max items (1–100)"
			}
		},
		"bulkCreateCards": {
			"boardId": {
				"type": "Board UUID",
				"required": true,
				"description": "Board UUID"
			},
			"cards": {
				"type": "unknown",
				"required": true,
				"description": ""
			}
		},
		"bulkMoveCards": {
			"boardId": {
				"type": "Board UUID",
				"required": true,
				"description": "Board UUID"
			},
			"cardIds": {
				"type": "UUIDs or #numbers",
				"required": true,
				"description": "UUIDs or #numbers"
			},
			"columnName": {
				"type": "Target column name",
				"required": true,
				"description": "Target column name"
			},
			"intent": {
				"type": "Why these cards are being moved (≤120 chars). Shown in the activity feed.",
				"required": true,
				"description": "Why these cards are being moved (≤120 chars). Shown in the activity feed."
			}
		},
		"bulkUpdateCards": {
			"cards": {
				"type": "unknown",
				"required": true,
				"description": ""
			}
		},
		"createCardFromTemplate": {
			"boardId": {
				"type": "Board UUID",
				"required": true,
				"description": "Board UUID"
			},
			"columnName": {
				"type": "Column name (e.g. 'Backlog')",
				"required": true,
				"description": "Column name (e.g. 'Backlog')"
			},
			"template": {
				"type": "unknown",
				"required": true,
				"description": ""
			},
			"title": {
				"type": "Card title (auto-prefixed with template type)",
				"required": true,
				"description": "Card title (auto-prefixed with template type)"
			}
		},
		"deleteCard": {
			"cardId": {
				"type": "Card UUID or #number",
				"required": true,
				"description": "Card UUID or #number"
			},
			"intent": {
				"type": "Short rationale for the deletion (e.g. 'duplicate of #41')",
				"required": true,
				"description": "Short rationale for the deletion (e.g. 'duplicate of #41')"
			},
			"boardId": {
				"type": "Board UUID — scopes #number resolution to this board's project",
				"required": false,
				"description": "Board UUID — scopes #number resolution to this board's project"
			}
		},
		"addChecklistItem": {
			"cardId": {
				"type": "Card UUID or #number",
				"required": true,
				"description": "Card UUID or #number"
			},
			"text": {
				"type": "Item text",
				"required": true,
				"description": "Item text"
			}
		},
		"bulkAddChecklistItems": {
			"cards": {
				"type": "Array of card + items pairs",
				"required": true,
				"description": "Array of card + items pairs"
			}
		},
		"toggleChecklistItem": {
			"checklistItemId": {
				"type": "UUID from getBoard (columns[].cards[].checklist.items[].id) or getCard",
				"required": true,
				"description": "UUID from getBoard (columns[].cards[].checklist.items[].id) or getCard"
			},
			"completed": {
				"type": "true=complete, false=incomplete",
				"required": true,
				"description": "true=complete, false=incomplete"
			}
		},
		"listComments": {
			"cardId": {
				"type": "Card UUID or #number",
				"required": true,
				"description": "Card UUID or #number"
			}
		},
		"getCardContext": {
			"boardId": {
				"type": "Board UUID",
				"required": true,
				"description": "Board UUID"
			},
			"cardId": {
				"type": "Card UUID or #number",
				"required": true,
				"description": "Card UUID or #number"
			},
			"format": {
				"type": "Response format",
				"required": false,
				"description": "Response format"
			}
		},
		"getMilestoneContext": {
			"boardId": {
				"type": "Board UUID",
				"required": true,
				"description": "Board UUID"
			},
			"milestone": {
				"type": "Milestone name",
				"required": true,
				"description": "Milestone name"
			},
			"format": {
				"type": "Response format",
				"required": false,
				"description": "Response format"
			}
		},
		"getTagContext": {
			"boardId": {
				"type": "Board UUID",
				"required": true,
				"description": "Board UUID"
			},
			"tag": {
				"type": "Tag label or slug — slugified for the lookup",
				"required": true,
				"description": "Tag label or slug — slugified for the lookup"
			},
			"format": {
				"type": "Response format",
				"required": false,
				"description": "Response format"
			}
		},
		"listClaims": {
			"projectId": {
				"type": "Project UUID",
				"required": true,
				"description": "Project UUID"
			},
			"claimId": {
				"type": "Fetch a single claim by UUID",
				"required": false,
				"description": "Fetch a single claim by UUID"
			},
			"kind": {
				"type": "Filter by kind",
				"required": false,
				"description": "Filter by kind"
			},
			"cardId": {
				"type": "Filter by card UUID or #number",
				"required": false,
				"description": "Filter by card UUID or #number"
			},
			"status": {
				"type": "Filter by status",
				"required": false,
				"description": "Filter by status"
			},
			"author": {
				"type": "Filter by author",
				"required": false,
				"description": "Filter by author"
			},
			"limit": {
				"type": "unknown",
				"required": false,
				"description": ""
			}
		},
		"listFacts": {
			"projectId": {
				"type": "Project UUID",
				"required": true,
				"description": "Project UUID"
			},
			"factId": {
				"type": "Fetch a single fact by UUID",
				"required": false,
				"description": "Fetch a single fact by UUID"
			},
			"type": {
				"type": "Filter by fact type",
				"required": false,
				"description": "Filter by fact type"
			},
			"path": {
				"type": "Filter by exact file path (code/measurement)",
				"required": false,
				"description": "Filter by exact file path (code/measurement)"
			},
			"pathPrefix": {
				"type": "Filter by path prefix (e.g. 'src/mcp/')",
				"required": false,
				"description": "Filter by path prefix (e.g. 'src/mcp/')"
			},
			"surface": {
				"type": "Filter context entries by surface level",
				"required": false,
				"description": "Filter context entries by surface level"
			},
			"needsRecheck": {
				"type": "(deprecated — no longer tracked; filter ignored)",
				"required": false,
				"description": "(deprecated — no longer tracked; filter ignored)"
			},
			"author": {
				"type": "Filter by author (AGENT or HUMAN)",
				"required": false,
				"description": "Filter by author (AGENT or HUMAN)"
			},
			"limit": {
				"type": "Max facts per type",
				"required": false,
				"description": "Max facts per type"
			}
		},
		"planCard": {
			"boardId": {
				"type": "Board UUID",
				"required": true,
				"description": "Board UUID"
			},
			"cardId": {
				"type": "Card UUID or #number",
				"required": true,
				"description": "Card UUID or #number"
			},
			"intent": {
				"type": "Optional rationale stamped on the activity strip (e.g. 'planning before standup')",
				"required": false,
				"description": "Optional rationale stamped on the activity strip (e.g. 'planning before standup')"
			}
		},
		"queryKnowledge": {
			"projectId": {
				"type": "Project UUID",
				"required": true,
				"description": "Project UUID"
			},
			"topic": {
				"type": "Search query — natural language or keywords",
				"required": true,
				"description": "Search query — natural language or keywords"
			},
			"limit": {
				"type": "Max results to return",
				"required": false,
				"description": "Max results to return"
			}
		},
		"rebuildKnowledgeIndex": {
			"projectId": {
				"type": "Project UUID",
				"required": true,
				"description": "Project UUID"
			}
		},
		"saveClaim": {
			"projectId": {
				"type": "Project UUID",
				"required": true,
				"description": "Project UUID"
			},
			"kind": {
				"type": "Claim kind",
				"required": true,
				"description": "Claim kind"
			},
			"statement": {
				"type": "One-sentence assertion (shown in lists)",
				"required": true,
				"description": "One-sentence assertion (shown in lists)"
			},
			"body": {
				"type": "Markdown elaboration",
				"required": false,
				"description": "Markdown elaboration"
			},
			"evidence": {
				"type": "Citations — files, symbols, urls, cardIds",
				"required": false,
				"description": "Citations — files, symbols, urls, cardIds"
			},
			"payload": {
				"type": "Kind-specific structured data — see description",
				"required": false,
				"description": "Kind-specific structured data — see description"
			},
			"author": {
				"type": "AGENT_NAME or HUMAN",
				"required": false,
				"description": "AGENT_NAME or HUMAN"
			},
			"cardId": {
				"type": "Card UUID or #number — optional anchor",
				"required": false,
				"description": "Card UUID or #number — optional anchor"
			},
			"status": {
				"type": "unknown",
				"required": false,
				"description": ""
			},
			"supersedesId": {
				"type": "Claim UUID this one replaces — old claim marked superseded and cross-linked",
				"required": false,
				"description": "Claim UUID this one replaces — old claim marked superseded and cross-linked"
			},
			"recordedAtSha": {
				"type": "Git SHA at record time (code/measurement)",
				"required": false,
				"description": "Git SHA at record time (code/measurement)"
			},
			"verifiedAt": {
				"type": "ISO datetime — defaults to now on create",
				"required": false,
				"description": "ISO datetime — defaults to now on create"
			},
			"expiresAt": {
				"type": "ISO datetime — TTL (measurement)",
				"required": false,
				"description": "ISO datetime — TTL (measurement)"
			},
			"claimId": {
				"type": "Claim UUID — pass to update",
				"required": false,
				"description": "Claim UUID — pass to update"
			}
		},
		"saveFact": {
			"type": {
				"type": "Fact type: context | code | measurement",
				"required": true,
				"description": "Fact type: context | code | measurement"
			},
			"projectId": {
				"type": "Project UUID",
				"required": true,
				"description": "Project UUID"
			},
			"content": {
				"type": "The fact text — maps to claim (context), fact (code), or description (measurement)",
				"required": true,
				"description": "The fact text — maps to claim (context), fact (code), or description (measurement)"
			},
			"author": {
				"type": "Who recorded this (AGENT or HUMAN)",
				"required": false,
				"description": "Who recorded this (AGENT or HUMAN)"
			},
			"path": {
				"type": "File path relative to repo root (required for code, optional for measurement)",
				"required": false,
				"description": "File path relative to repo root (required for code, optional for measurement)"
			},
			"symbol": {
				"type": "Symbol name (function, class, variable)",
				"required": false,
				"description": "Symbol name (function, class, variable)"
			},
			"recordedAtSha": {
				"type": "Git SHA when this was recorded",
				"required": false,
				"description": "Git SHA when this was recorded"
			},
			"factId": {
				"type": "Fact UUID — pass to update an existing fact",
				"required": false,
				"description": "Fact UUID — pass to update an existing fact"
			},
			"rationale": {
				"type": "[context] Why this matters",
				"required": false,
				"description": "[context] Why this matters"
			},
			"application": {
				"type": "[context] How to apply this knowledge",
				"required": false,
				"description": "[context] How to apply this knowledge"
			},
			"details": {
				"type": "[context] Supporting details",
				"required": false,
				"description": "[context] Supporting details"
			},
			"audience": {
				"type": "[context] Who should see it (all, agent, human)",
				"required": false,
				"description": "[context] Who should see it (all, agent, human)"
			},
			"citedFiles": {
				"type": "[context] File paths this fact references",
				"required": false,
				"description": "[context] File paths this fact references"
			},
			"surface": {
				"type": "[context] Visibility: ambient | indexed | surfaced",
				"required": false,
				"description": "[context] Visibility: ambient | indexed | surfaced"
			},
			"value": {
				"type": "[measurement] Numeric value",
				"required": false,
				"description": "[measurement] Numeric value"
			},
			"unit": {
				"type": "[measurement] Unit (e.g. ms, MB, s, bytes)",
				"required": false,
				"description": "[measurement] Unit (e.g. ms, MB, s, bytes)"
			},
			"env": {
				"type": "[measurement] Environment key-value pairs",
				"required": false,
				"description": "[measurement] Environment key-value pairs"
			},
			"recordedAt": {
				"type": "[measurement] ISO 8601 when measured (defaults to now)",
				"required": false,
				"description": "[measurement] ISO 8601 when measured (defaults to now)"
			},
			"ttl": {
				"type": "[measurement] Time-to-live in days",
				"required": false,
				"description": "[measurement] Time-to-live in days"
			}
		},
		"getDecisions": {
			"projectId": {
				"type": "Project UUID",
				"required": true,
				"description": "Project UUID"
			},
			"cardId": {
				"type": "Card UUID or #number",
				"required": false,
				"description": "Card UUID or #number"
			},
			"status": {
				"type": "unknown",
				"required": false,
				"description": ""
			}
		},
		"recordDecision": {
			"projectId": {
				"type": "Project UUID",
				"required": true,
				"description": "Project UUID"
			},
			"cardId": {
				"type": "Card UUID or #number",
				"required": false,
				"description": "Card UUID or #number"
			},
			"title": {
				"type": "Decision title",
				"required": true,
				"description": "Decision title"
			},
			"status": {
				"type": "unknown",
				"required": false,
				"description": ""
			},
			"decision": {
				"type": "The decision text",
				"required": true,
				"description": "The decision text"
			},
			"alternatives": {
				"type": "Alternatives considered",
				"required": false,
				"description": "Alternatives considered"
			},
			"rationale": {
				"type": "Why this decision was made",
				"required": false,
				"description": "Why this decision was made"
			},
			"supersedesId": {
				"type": "ID of the decision this one supersedes — the old decision will be marked as superseded and linked",
				"required": false,
				"description": "ID of the decision this one supersedes — the old decision will be marked as superseded and linked"
			}
		},
		"updateDecision": {
			"decisionId": {
				"type": "Decision UUID",
				"required": true,
				"description": "Decision UUID"
			},
			"status": {
				"type": "unknown",
				"required": false,
				"description": ""
			},
			"decision": {
				"type": "Updated decision text",
				"required": false,
				"description": "Updated decision text"
			},
			"rationale": {
				"type": "Updated rationale",
				"required": false,
				"description": "Updated rationale"
			},
			"alternatives": {
				"type": "Updated alternatives",
				"required": false,
				"description": "Updated alternatives"
			},
			"supersedesId": {
				"type": "ID of the decision this one supersedes — sets old decision to superseded and links them",
				"required": false,
				"description": "ID of the decision this one supersedes — sets old decision to superseded and links them"
			}
		},
		"doctor": {},
		"auditBoard": {
			"boardId": {
				"type": "Board UUID",
				"required": true,
				"description": "Board UUID"
			},
			"excludeDone": {
				"type": "Skip Done/Parking columns (default true)",
				"required": false,
				"description": "Skip Done/Parking columns (default true)"
			},
			"weights": {
				"type": "unknown",
				"required": false,
				"description": ""
			}
		},
		"getBoard": {
			"boardId": {
				"type": "Board UUID",
				"required": true,
				"description": "Board UUID"
			},
			"format": {
				"type": "'json' (default) or 'toon' (flat tabular shapes only — loses on nested payloads)",
				"required": false,
				"description": "'json' (default) or 'toon' (flat tabular shapes only — loses on nested payloads)"
			},
			"columns": {
				"type": "Only include these columns by name (e.g. ['Backlog', 'In Progress'])",
				"required": false,
				"description": "Only include these columns by name (e.g. ['Backlog', 'In Progress'])"
			},
			"excludeDone": {
				"type": "Exclude columns with role 'done' or 'parking' — great for reducing payload",
				"required": false,
				"description": "Exclude columns with role 'done' or 'parking' — great for reducing payload"
			},
			"summary": {
				"type": "Lightweight mode: returns only ref, title, priority, tags, milestone, checklist counts — no descriptions or checklist items.",
				"required": false,
				"description": "Lightweight mode: returns only ref, title, priority, tags, milestone, checklist counts — no descriptions or checklist items."
			}
		},
		"getCard": {
			"cardId": {
				"type": "Card UUID or #number",
				"required": true,
				"description": "Card UUID or #number"
			},
			"format": {
				"type": "'json' (default) or 'toon' (flat tabular shapes only)",
				"required": false,
				"description": "'json' (default) or 'toon' (flat tabular shapes only)"
			}
		},
		"getRoadmap": {
			"boardId": {
				"type": "Board UUID",
				"required": true,
				"description": "Board UUID"
			},
			"format": {
				"type": "'json' (default) or 'toon' (flat tabular shapes only — loses on nested payloads)",
				"required": false,
				"description": "'json' (default) or 'toon' (flat tabular shapes only — loses on nested payloads)"
			}
		},
		"getStats": {
			"boardId": {
				"type": "Board UUID",
				"required": true,
				"description": "Board UUID"
			}
		},
		"getToolUsageStats": {
			"mode": {
				"type": "summary=top tools overview, tool=single tool deep dive, agents=per-agent breakdown",
				"required": false,
				"description": "summary=top tools overview, tool=single tool deep dive, agents=per-agent breakdown"
			},
			"toolName": {
				"type": "Required for mode=tool. Exact tool name (e.g. 'getBoard', 'createCard')",
				"required": false,
				"description": "Required for mode=tool. Exact tool name (e.g. 'getBoard', 'createCard')"
			},
			"since": {
				"type": "ISO date string — only include logs after this time. Defaults to last 7 days.",
				"required": false,
				"description": "ISO date string — only include logs after this time. Defaults to last 7 days."
			}
		},
		"getWorkNextSuggestion": {
			"boardId": {
				"type": "Board UUID",
				"required": true,
				"description": "Board UUID"
			},
			"limit": {
				"type": "How many suggestions (1-20, default 5)",
				"required": false,
				"description": "How many suggestions (1-20, default 5)"
			}
		},
		"listBoards": {
			"projectId": {
				"type": "Project UUID",
				"required": true,
				"description": "Project UUID"
			}
		},
		"listProjects": {},
		"listWorkflows": {
			"boardId": {
				"type": "Board UUID — when present, the response includes a state-aware `suggested` workflow.",
				"required": false,
				"description": "Board UUID — when present, the response includes a state-aware `suggested` workflow."
			},
			"name": {
				"type": "Filter to a single workflow by name (e.g. 'sessionStart')",
				"required": false,
				"description": "Filter to a single workflow by name (e.g. 'sessionStart')"
			}
		},
		"queryCards": {
			"boardId": {
				"type": "Board UUID",
				"required": true,
				"description": "Board UUID"
			},
			"priority": {
				"type": "Filter by priority level",
				"required": false,
				"description": "Filter by priority level"
			},
			"columnName": {
				"type": "Filter by column name",
				"required": false,
				"description": "Filter by column name"
			},
			"tags": {
				"type": "Filter cards that have ALL specified tags",
				"required": false,
				"description": "Filter cards that have ALL specified tags"
			},
			"milestoneName": {
				"type": "Filter by milestone name",
				"required": false,
				"description": "Filter by milestone name"
			},
			"createdBefore": {
				"type": "Cards created before this ISO datetime",
				"required": false,
				"description": "Cards created before this ISO datetime"
			},
			"updatedBefore": {
				"type": "Cards updated before this ISO datetime",
				"required": false,
				"description": "Cards updated before this ISO datetime"
			},
			"staleDays": {
				"type": "Cards not updated in N days",
				"required": false,
				"description": "Cards not updated in N days"
			},
			"hasBlockers": {
				"type": "Only cards with blockedBy relations",
				"required": false,
				"description": "Only cards with blockedBy relations"
			},
			"limit": {
				"type": "Max results (1-200, default 50)",
				"required": false,
				"description": "Max results (1-200, default 50)"
			}
		},
		"renderStatus": {
			"projectId": {
				"type": "Project UUID",
				"required": true,
				"description": "Project UUID"
			}
		},
		"searchCards": {
			"query": {
				"type": "Text to match in title and description",
				"required": true,
				"description": "Text to match in title and description"
			},
			"tag": {
				"type": "Tag label or slug — slugified for the lookup",
				"required": false,
				"description": "Tag label or slug — slugified for the lookup"
			}
		},
		"getCommitSummary": {
			"cardId": {
				"type": "Card UUID or #number",
				"required": true,
				"description": "Card UUID or #number"
			}
		},
		"getGitLog": {
			"projectId": {
				"type": "Project UUID",
				"required": true,
				"description": "Project UUID"
			},
			"limit": {
				"type": "Max commits (1–100)",
				"required": false,
				"description": "Max commits (1–100)"
			}
		},
		"syncGitActivity": {
			"projectId": {
				"type": "Project UUID",
				"required": true,
				"description": "Project UUID"
			},
			"since": {
				"type": "ISO datetime, git date string like '2 weeks ago', or 'all' for full history",
				"required": false,
				"description": "ISO datetime, git date string like '2 weeks ago', or 'all' for full history"
			}
		},
		"createMilestone": {
			"projectId": {
				"type": "Project UUID",
				"required": true,
				"description": "Project UUID"
			},
			"name": {
				"type": "e.g. 'MVP', 'v1.1', 'Q2 Launch'",
				"required": true,
				"description": "e.g. 'MVP', 'v1.1', 'Q2 Launch'"
			},
			"description": {
				"type": "unknown",
				"required": false,
				"description": ""
			},
			"targetDate": {
				"type": "ISO 8601",
				"required": false,
				"description": "ISO 8601"
			}
		},
		"listMilestones": {
			"projectId": {
				"type": "Project UUID",
				"required": true,
				"description": "Project UUID"
			}
		},
		"mergeMilestones": {
			"fromMilestoneId": {
				"type": "Source milestone UUID — deleted after merge",
				"required": true,
				"description": "Source milestone UUID — deleted after merge"
			},
			"intoMilestoneId": {
				"type": "Destination milestone UUID — kept",
				"required": true,
				"description": "Destination milestone UUID — kept"
			}
		},
		"updateMilestone": {
			"milestoneId": {
				"type": "UUID from getRoadmap or listMilestones",
				"required": true,
				"description": "UUID from getRoadmap or listMilestones"
			},
			"name": {
				"type": "unknown",
				"required": false,
				"description": ""
			},
			"description": {
				"type": "null to clear",
				"required": false,
				"description": "null to clear"
			},
			"targetDate": {
				"type": "ISO 8601, null to clear",
				"required": false,
				"description": "ISO 8601, null to clear"
			},
			"state": {
				"type": "v4.2: 'archived' hides from picker (cards keep their assignment).",
				"required": false,
				"description": "v4.2: 'archived' hides from picker (cards keep their assignment)."
			}
		},
		"createNote": {
			"title": {
				"type": "unknown",
				"required": true,
				"description": ""
			},
			"content": {
				"type": "Markdown",
				"required": false,
				"description": "Markdown"
			},
			"tags": {
				"type": "unknown",
				"required": false,
				"description": ""
			},
			"projectId": {
				"type": "Project UUID, omit for global",
				"required": false,
				"description": "Project UUID, omit for global"
			},
			"kind": {
				"type": "unknown",
				"required": false,
				"description": ""
			},
			"author": {
				"type": "AGENT_NAME or HUMAN",
				"required": false,
				"description": "AGENT_NAME or HUMAN"
			},
			"cardId": {
				"type": "Card UUID or #number (requires projectId for #N form)",
				"required": false,
				"description": "Card UUID or #number (requires projectId for #N form)"
			},
			"boardId": {
				"type": "Board UUID",
				"required": false,
				"description": "Board UUID"
			},
			"metadata": {
				"type": "Kind-specific metadata",
				"required": false,
				"description": "Kind-specific metadata"
			},
			"expiresAt": {
				"type": "ISO datetime — optional TTL",
				"required": false,
				"description": "ISO datetime — optional TTL"
			}
		},
		"listNotes": {
			"projectId": {
				"type": "Project UUID, omit for all",
				"required": false,
				"description": "Project UUID, omit for all"
			},
			"kind": {
				"type": "Filter by kind",
				"required": false,
				"description": "Filter by kind"
			},
			"cardId": {
				"type": "Card UUID or #number (requires projectId for #N form)",
				"required": false,
				"description": "Card UUID or #number (requires projectId for #N form)"
			},
			"boardId": {
				"type": "Board UUID",
				"required": false,
				"description": "Board UUID"
			},
			"author": {
				"type": "Filter by author (AGENT_NAME or HUMAN)",
				"required": false,
				"description": "Filter by author (AGENT_NAME or HUMAN)"
			}
		},
		"updateNote": {
			"noteId": {
				"type": "UUID from listNotes",
				"required": true,
				"description": "UUID from listNotes"
			},
			"title": {
				"type": "unknown",
				"required": false,
				"description": ""
			},
			"content": {
				"type": "Markdown",
				"required": false,
				"description": "Markdown"
			},
			"tags": {
				"type": "Replaces all tags",
				"required": false,
				"description": "Replaces all tags"
			},
			"kind": {
				"type": "unknown",
				"required": false,
				"description": ""
			},
			"author": {
				"type": "unknown",
				"required": false,
				"description": ""
			},
			"cardId": {
				"type": "Card UUID, #number, or null to unset",
				"required": false,
				"description": "Card UUID, #number, or null to unset"
			},
			"boardId": {
				"type": "Board UUID or null to unset",
				"required": false,
				"description": "Board UUID or null to unset"
			},
			"metadata": {
				"type": "Replaces metadata blob",
				"required": false,
				"description": "Replaces metadata blob"
			},
			"expiresAt": {
				"type": "ISO datetime or null to unset",
				"required": false,
				"description": "ISO datetime or null to unset"
			},
			"projectId": {
				"type": "Project UUID — only for resolving #N cardId",
				"required": false,
				"description": "Project UUID — only for resolving #N cardId"
			}
		},
		"getBlockers": {
			"boardId": {
				"type": "Board UUID — omit to search all boards",
				"required": false,
				"description": "Board UUID — omit to search all boards"
			}
		},
		"linkCards": {
			"cardId": {
				"type": "Card UUID or #number",
				"required": true,
				"description": "Card UUID or #number"
			},
			"targetCardId": {
				"type": "Card UUID or #number",
				"required": true,
				"description": "Card UUID or #number"
			},
			"type": {
				"type": "blocks = cardId blocks targetCardId, related = bidirectional, parent = cardId is parent of targetCardId",
				"required": true,
				"description": "blocks = cardId blocks targetCardId, related = bidirectional, parent = cardId is parent of targetCardId"
			}
		},
		"unlinkCards": {
			"cardId": {
				"type": "Card UUID or #number",
				"required": true,
				"description": "Card UUID or #number"
			},
			"targetCardId": {
				"type": "Card UUID or #number",
				"required": true,
				"description": "Card UUID or #number"
			},
			"type": {
				"type": "Relation type to remove",
				"required": true,
				"description": "Relation type to remove"
			}
		},
		"listHandoffs": {
			"boardId": {
				"type": "Board UUID",
				"required": true,
				"description": "Board UUID"
			},
			"limit": {
				"type": "Number of recent handoffs to return",
				"required": false,
				"description": "Number of recent handoffs to return"
			}
		},
		"loadHandoff": {
			"boardId": {
				"type": "Board UUID",
				"required": true,
				"description": "Board UUID"
			}
		},
		"recordTokenUsage": {
			"projectId": {
				"type": "Project UUID (omit if boardId is set)",
				"required": false,
				"description": "Project UUID (omit if boardId is set)"
			},
			"boardId": {
				"type": "Board UUID (resolves to projectId — convenience for board-scoped agents)",
				"required": false,
				"description": "Board UUID (resolves to projectId — convenience for board-scoped agents)"
			},
			"sessionId": {
				"type": "Session identifier (defaults to MCP server SESSION_ID)",
				"required": false,
				"description": "Session identifier (defaults to MCP server SESSION_ID)"
			},
			"cardId": {
				"type": "Optional card UUID for card-level attribution",
				"required": false,
				"description": "Optional card UUID for card-level attribution"
			},
			"agentName": {
				"type": "Agent identifier (defaults to AGENT_NAME)",
				"required": false,
				"description": "Agent identifier (defaults to AGENT_NAME)"
			},
			"model": {
				"type": "Model identifier — must match a key in pricing settings",
				"required": true,
				"description": "Model identifier — must match a key in pricing settings"
			},
			"inputTokens": {
				"type": "Input tokens consumed",
				"required": true,
				"description": "Input tokens consumed"
			},
			"outputTokens": {
				"type": "Output tokens generated",
				"required": true,
				"description": "Output tokens generated"
			},
			"cacheReadTokens": {
				"type": "Cache read tokens (default 0)",
				"required": false,
				"description": "Cache read tokens (default 0)"
			},
			"cacheCreation1hTokens": {
				"type": "1-hour cache creation tokens (Anthropic; default 0)",
				"required": false,
				"description": "1-hour cache creation tokens (Anthropic; default 0)"
			},
			"cacheCreation5mTokens": {
				"type": "5-minute cache creation tokens (Anthropic; default 0)",
				"required": false,
				"description": "5-minute cache creation tokens (Anthropic; default 0)"
			}
		},
		"recordTokenUsageFromTranscript": {
			"transcriptPath": {
				"type": "Absolute path to the session JSONL transcript",
				"required": true,
				"description": "Absolute path to the session JSONL transcript"
			},
			"sessionId": {
				"type": "Claude Code session UUID (distinct from the MCP server's SESSION_ID)",
				"required": true,
				"description": "Claude Code session UUID (distinct from the MCP server's SESSION_ID)"
			},
			"cwd": {
				"type": "Working directory the session ran in — resolved to a registered project",
				"required": true,
				"description": "Working directory the session ran in — resolved to a registered project"
			},
			"cardId": {
				"type": "Optional card UUID for card-level attribution",
				"required": false,
				"description": "Optional card UUID for card-level attribution"
			}
		},
		"createColumn": {
			"boardId": {
				"type": "Board UUID",
				"required": true,
				"description": "Board UUID"
			},
			"name": {
				"type": "unknown",
				"required": true,
				"description": ""
			},
			"description": {
				"type": "unknown",
				"required": false,
				"description": ""
			}
		},
		"createProject": {
			"name": {
				"type": "unknown",
				"required": true,
				"description": ""
			},
			"description": {
				"type": "unknown",
				"required": false,
				"description": ""
			},
			"boardName": {
				"type": "unknown",
				"required": false,
				"description": ""
			}
		},
		"seedTutorial": {},
		"setRepoPath": {
			"projectId": {
				"type": "Project UUID",
				"required": true,
				"description": "Project UUID"
			},
			"repoPath": {
				"type": "Absolute path to local git repo",
				"required": true,
				"description": "Absolute path to local git repo"
			}
		},
		"createTag": {
			"projectId": {
				"type": "Project UUID",
				"required": true,
				"description": "Project UUID"
			},
			"label": {
				"type": "Display label — slugified for the canonical identifier",
				"required": true,
				"description": "Display label — slugified for the canonical identifier"
			}
		},
		"deleteTag": {
			"tagId": {
				"type": "Tag UUID — must be an orphan (usageCount === 0)",
				"required": true,
				"description": "Tag UUID — must be an orphan (usageCount === 0)"
			}
		},
		"listTags": {
			"projectId": {
				"type": "Project UUID",
				"required": true,
				"description": "Project UUID"
			},
			"state": {
				"type": "Filter by tag state. Defaults to 'active' when omitted.",
				"required": false,
				"description": "Filter by tag state. Defaults to 'active' when omitted."
			}
		},
		"mergeTags": {
			"fromTagId": {
				"type": "Source tag UUID — deleted after merge",
				"required": true,
				"description": "Source tag UUID — deleted after merge"
			},
			"intoTagId": {
				"type": "Destination tag UUID — kept",
				"required": true,
				"description": "Destination tag UUID — kept"
			}
		},
		"renameTag": {
			"tagId": {
				"type": "Tag UUID",
				"required": true,
				"description": "Tag UUID"
			},
			"label": {
				"type": "New display label",
				"required": true,
				"description": "New display label"
			}
		}
	}
};
